//
//  Hint.swift
//  Netrek
//
//  Created by Darrell Root on 3/30/19.
//  Copyright © 2019 Network Mom LLC. All rights reserved.
//

import Foundation

var BasicHints = [
    /* hints larger than 68 characters will result in crash due to max SKTexture size
     "01234567890123456789012345678901234567890123456789012345678901234567",
     */
    "To start game, select a server, then launch ship -> cruiser",
    "It may be necessary to select a different preferred team",
    "Left mouse button fires torpedoes",
    "Right mouse button sets direction",
    "Number keys set speed",
    "Middle mouse button fires laser",
    "s raises or lowers your shields",
]

var AdvancedHints = [
    /* hints larger than 68 characters will result in crash due to max SKTexture size
     "01234567890123456789012345678901234567890123456789012345678901234567",
    */
    "l locks your destination onto a planet or ship",
    "b bombs an enemy planet you are orbiting",
    "R stops and repairs your ship",
    "Enemy planets damage you when you are close",
    "You can carry 2 armies for each kill with your current ship",
    "There are 40 planets in the universe",
    "There are 2 active species in the game",
    "There are 2 inactive species in the game",
    "Each species starts with 10 planets",
    "Tournament mode will start when sufficient humans  play",
    "Tournament stats and ranks are only earned in tournament mode",
    "Work with your team to capture planets",
    "c activates your cloaking device",
    "Controls can be customized in the preferences",
    "When low on planets, let more experienced players pick the armies",
    "When your team has many armies, do not be afraid to use them",
    "The team that delivers the most armies wins",
    "Have flexible goals",
    "Killing an opponent with a buddy is easier then doing it on your own",
    "Go for the open planet when you are carrying",
    "It is dangerous to underestimate opponents",
    "It is dangerous to overestimate teammates",
    "Sometimes you just have to hope that they miss",
    "Do not cloak in your own backfield; you will fool your teammates",
    "Send a distress call after you pick up armies to get help",
    "Escorts should stay between the ogger and the carrier",
    "Never kill an ogger who is out of fuel or crippled",
    "Get near their planets",
    "Use the space people give away when running",
    "Think globally and act locally",
    "You are not PacMan: do not eat the dots",
    "Watch the galactic map: situational awareness wins",
    "Tractor enemies off planets",
    "Never pass up an opportunity to bomb",
    "You cannot be everywhere at once",
    "Do not fixate on one target",
    "Planning is good, but opportunism is better",
    "If an enemy is annoying you, consider adopting his strategy",
    "Do not argue about which planet to take",
    "Nobody completely understands the game. Certainly not you.",
    "Do not tell others what to do",
    "Do not waste your fuel firing torpedos that the enemy will dodge",
    "Nobody can dodge lasers",
    "You should do the easy things first",
    "Shoot the escort first",
    "Try to fight past the enemy's front-line planets",
    "Death is only a temporary setback",
    "Lasers are better than torpedoes, but torpedoes go farther",
    "You should not keep beating your head against the same wall",
    "You can run from multiple oggers almost as easily as from one",
    "You should never go out to third space to escort",
    "You cannot make your teammates more clueful without their help",
    "You should not chase ships. Occupy the space they left",
    "Do not fly to lost plays. Do something more useful instead",
    "If you carry armies, go to a different planet than other carriers",
    "You should not react to their game, but play your own game",
    "If you laser every second you'll win most dogfights",
    "Lasers have a constant cycle time",
    "Skill does not equal clue",
    "Cloaking does not make you invincible",
    "Fuel is your friend. Treasure it",
    "You can det for a carrier even if you are almost out of fuel",
    "Detting only takes 100 fuel",
    "Dying is the fastest way of repairing and refueling",
    "The best way to defend a starbase is to attack the enemy oggers",
    "Rank does not equal clue",
    "Practice makes perfect",
    "Nobody said this was easy",
    "There is no I in team",
    "It is always a good idea to fly into enemy space",
    "You should never let an enemy CA live in your backfield",
    "You should never chase a SC bomber with 0 kills. You can't catch it",
    "If you feel useless, grab a SC and start SC bombing",
    "When you are SC bombing, bomb as many armies as possible",
    "If a starbase dies, it takes 30 minutes to get a new one",
    "Playing a starbase well is a unique skill",
    "Destroying an enemy starbase requires multiple ships",
    "Information is the most valuable commodity in netrek. Communicate!",
    "Do not be afraid to admit you messed up. Everyone else already knows",
    "Everyone has a bad day, try not to take things personally",
    "Watch the good players and learn from them",
    "Lasers do more damage to close targets",
    "Torpedo damage does not change based on range",
    "A cruiser CA can fly speed 9, has 10000 fuel, 100 hull, 100 shields",
    "A cruiser CA has 40 point torps and can do up to 100 pt laser damage",
    "Assault ship AS can fly speed 8, has 6000 fuel, 200 hull, 80 shields",
    "Assault ship AS has 30 pt torps and up to 80 pt max laser damage",
    "A battleship BB can fly speed 8, has 14000 fuel 130 hull 130 shield",
    "A battleship BB has 40 pt torps and can do up to 105 pt laser damage",
    "A scout SC, can fly speed 12, has 5000 fuel, 75 hull, 75 shields",
    "A scout SC has 25 pt torps and can do up to 75 pt laser damage",
    "A destroyer DD, can fly speed 10, has 7000 fuel, 85 hull, 85 shields",
    "A destroyer has 30 pt torps and can do 85 pt maximum laser damage",
    "A starbase SB can fly speed 2, has 60000 fuel, 600 hull, 500 shields",
    "A starbase SB has 30 pt torps and can do up to 120 pt laser damage",
    "Assault ships are mainly used for taking heavily guarded planets",
    "Battleships have strong firepower but use fuel quickly",
    "Cruisers are well rounded, having good firepower and maneuverability",
    "In most situations, a cruiser is the right ship choice",
    "Scouts are best used for bombing or taking",
    "Scouts are too brittle to be used for space controlling",
    "Starbases can fire phasers more than twice as fast as any other ship",
    "'Ogg' means a suicide attack against an enemy ship",
    "'doosh' means, killing an enemy ship which is carrying armies"
]

